### ISSUE TITLE
No workflow file in /Ch03 /03_04_ci_cd_for_container_images/

### ISSUE THREAD

**Issue by glenrose83** [LinkedInLearning/github-actions-for-ci-cd-4375061#3]
## Issue Overview
No workflow file in lesson /Ch03 /03_04_ci_cd_for_container_images/

## Steps to Reproduce

1. what the video

## Expected Behavior
A  workflow file as in the video

## Possible Solution
Upload workflow file

## Related Issues

In the lesson 03_03 I get a error when running the flow due to node i depecated.  I should now use v. 20 but dont know how.

**Comment by managedkaos** [comment]
The workflow file is not provided as the intent for the lab is for the user to find and implement the workflow provided by GitHub using these steps:

```
3. In the repo select the Actions tab.
4. Select and configure the workflow Publish Docker Container.
```

For `node` deprecations, follow the steps under [Fixing Warnings in the Annotations Section](https://github.com/LinkedInLearning/github-actions-for-ci-cd-4375061/tree/main/Ch03/03_04_ci_cd_for_container_images#fixing-warnings-in-the-annotations-section)

**Comment by glenrose83** [comment]
Thanks for the help!

ons. 12. jun. 2024 kl. 19.22 skrev Michael ***@***.***>:
